const themes = [
  {
    id: 'warmearth',
    name: 'Warm Earth',
    description: 'Warm tones, approachable, friendly',
    vars: {
      '--color-bg': '#1c1714',
      '--color-bg-elevated': '#252019',
      '--color-text': '#f2ebe0',
      '--color-text-muted': '#a0937e',
      '--color-accent': '#c87533',
      '--color-border': '#3a322a',
      '--font-heading': "'Syne', sans-serif",
      '--font-body': "'Public Sans', sans-serif",
      '--card-radius': '16px',
      '--hero-overlay': 'linear-gradient(135deg, rgba(28,23,20,0.75), rgba(200,117,51,0.12))',
    },
  },
  {
    id: 'kinetic',
    name: 'Kinetic',
    description: 'Animation showcase — springs, parallax, stagger',
    vars: {
      '--color-bg': '#0f0f1a',
      '--color-bg-elevated': '#16162a',
      '--color-text': '#eeeeff',
      '--color-text-muted': '#7777aa',
      '--color-accent': '#f7931a',
      '--color-border': '#25254a',
      '--font-heading': "'Space Grotesk', sans-serif",
      '--font-body': "'Inter', sans-serif",
      '--card-radius': '12px',
      '--hero-overlay': 'linear-gradient(135deg, rgba(15,15,26,0.7), rgba(247,147,26,0.1))',
    },
  },
  {
    id: 'default',
    name: 'Default',
    description: 'Original BEI dark theme',
    vars: {
      '--color-bg': '#161616',
      '--color-bg-elevated': '#1e1e1e',
      '--color-text': '#f7f7f7',
      '--color-text-muted': '#a0a0a0',
      '--color-accent': '#f7931a',
      '--color-border': '#333',
      '--font-heading': "'Fjalla One', sans-serif",
      '--font-body': "'Source Sans 3', 'Source Sans Pro', sans-serif",
      '--card-radius': '8px',
      '--hero-overlay': 'linear-gradient(rgba(0,0,0,0.65), rgba(0,0,0,0.65))',
    },
  },
  {
    id: 'btcpolicy',
    name: 'BTC Policy',
    description: 'Inspired by Bitcoin Policy Institute — editorial, authoritative',
    vars: {
      '--color-bg': '#121118',
      '--color-bg-elevated': '#1c1b22',
      '--color-text': '#f0f0f0',
      '--color-text-muted': '#9e9bab',
      '--color-accent': '#4d65ff',
      '--color-border': '#2a2935',
      '--font-heading': "'Source Serif 4', Georgia, serif",
      '--font-body': "'Public Sans', sans-serif",
      '--card-radius': '6px',
      '--hero-overlay': 'linear-gradient(135deg, rgba(18,17,24,0.85), rgba(77,101,255,0.15))',
    },
  },
  {
    id: 'whitepaper',
    name: 'Whitepaper',
    description: 'Clean, light, academic — like reading the Bitcoin whitepaper',
    vars: {
      '--color-bg': '#faf8f5',
      '--color-bg-elevated': '#ffffff',
      '--color-text': '#1a1a1a',
      '--color-text-muted': '#5a5a5a',
      '--color-accent': '#e67e22',
      '--color-border': '#e0dcd5',
      '--font-heading': "'Bitter', Georgia, serif",
      '--font-body': "'Public Sans', sans-serif",
      '--card-radius': '8px',
      '--hero-overlay': 'linear-gradient(rgba(250,248,245,0.85), rgba(250,248,245,0.85))',
    },
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    description: 'Raw, oversized type, hard edges',
    vars: {
      '--color-bg': '#000000',
      '--color-bg-elevated': '#0a0a0a',
      '--color-text': '#ffffff',
      '--color-text-muted': '#888888',
      '--color-accent': '#ff4400',
      '--color-border': '#333333',
      '--font-heading': "'Archivo Black', sans-serif",
      '--font-body': "'Inter', sans-serif",
      '--card-radius': '0px',
      '--hero-overlay': 'linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5))',
    },
  },
];

export default themes;
